# Generated by Django 5.1.4 on 2025-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0027_alter_contactus_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='termsandcondition',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
