# Generated by Django 5.1.4 on 2025-09-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0074_texteditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='text_editors',
            field=models.ManyToManyField(to='product.texteditor'),
        ),
    ]
