# Generated by Django 5.1.4 on 2025-09-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_remove_company_facebook_remove_company_linkedin_and_more'),
        ('product', '0075_multipage_text_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sub_categories', to='company.company'),
        ),
    ]
