# Generated by Django 5.1.4 on 2025-09-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_alter_subcategory_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipage',
            name='meta_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productdetailpage',
            name='meta_title',
            field=models.CharField(max_length=500),
        ),
    ]
