# Generated by Django 5.1.4 on 2025-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_alter_multipage_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='bulletpoint',
            name='bullet_point',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='bullet_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='product_region',
            field=models.CharField(default='all', max_length=500),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='timeline_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagebulletpoint',
            name='bullet_point',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagebulletpoint',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagefaq',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagefaq',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagefeature',
            name='feature',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagefeature',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagetimeline',
            name='heading',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagetimeline',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='productdetailpage',
            name='timeline_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='standard',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='texteditor',
            name='text_editor_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='texteditor',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='heading',
            field=models.CharField(max_length=500),
        ),
    ]
