# Generated by Django 5.1.4 on 2025-09-27 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0037_client_url'),
        ('product', '0080_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_faqs', to='company.company'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='product.product'),
        ),
    ]
