# Generated by Django 5.1.4 on 2025-11-11 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_clientslider'),
        ('product', '0081_alter_faq_company_alter_faq_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='ending_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='hide_faqs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='location_slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='starting_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SubCategoryFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_faqs', to='company.company')),
            ],
            options={
                'db_table': 'sub_category_faqs',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='subcategory',
            name='faqs',
            field=models.ManyToManyField(to='product.subcategoryfaq'),
        ),
    ]
