# Generated by Django 5.1.4 on 2025-09-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blog_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='course',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='product',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='service',
        ),
    ]
