# Generated by Django 5.1.4 on 2025-09-01 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_blog_course_remove_blog_product_and_more'),
        ('educational', '0155_alter_coursedetail_company'),
        ('product', '0070_alter_productdetailpage_company'),
        ('registration', '0055_alter_registrationdetailpage_company_and_more'),
        ('service', '0054_alter_servicedetail_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='product_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='blog',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational.program'),
        ),
        migrations.AddField(
            model_name='blog',
            name='registration_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='registration.registrationsubtype'),
        ),
        migrations.AddField(
            model_name='blog',
            name='service_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.subcategory'),
        ),
    ]
