# Generated by Django 5.1.4 on 2025-09-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blog_product_sub_category_blog_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='product_sub_category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='program',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='service_sub_category',
        ),
    ]
