# Generated by Django 5.1.4 on 2025-09-16 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_blog_product_sub_category_remove_blog_program_and_more'),
        ('company', '0034_alter_company_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='company.company'),
        ),
    ]
