# Generated by Django 5.1.4 on 2025-09-25 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0037_client_url'),
        ('service', '0059_alter_bulletpoints_bullet_point_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_faqs', to='company.company'),
        ),
        migrations.AlterField(
            model_name='multipagefaq',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_multi_faqs', to='company.company'),
        ),
    ]
