# Generated by Django 5.1.4 on 2025-09-25 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0060_alter_faq_company_alter_multipagefaq_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_faqs', to='service.service'),
        ),
    ]
