# Generated by Django 5.1.4 on 2025-09-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0155_alter_coursedetail_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='meta_tags',
        ),
    ]
