# Generated by Django 5.1.4 on 2025-09-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_metatag_meta_description_metatag_meta_title'),
        ('educational', '0156_remove_course_meta_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meta_tags',
            field=models.ManyToManyField(to='base.metatag'),
        ),
    ]
