# Generated by Django 5.1.4 on 2025-09-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_remove_company_facebook_remove_company_linkedin_and_more'),
        ('educational', '0158_alter_course_duration_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='company.company'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='company.company'),
        ),
    ]
