# Generated by Django 5.1.4 on 2025-09-23 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0163_alter_bulletpoints_bullet_point_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_testimonials', to='educational.course'),
        ),
    ]
