# Generated by Django 5.1.4 on 2025-09-06 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_remove_company_facebook_remove_company_linkedin_and_more'),
        ('registration', '0055_alter_registrationdetailpage_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text_editor_title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_editors', to='company.company')),
            ],
            options={
                'db_table': 'text_editors',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='multipage',
            name='text_ediots',
            field=models.ManyToManyField(to='registration.texteditor'),
        ),
    ]
