# Generated by Django 5.1.4 on 2025-09-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0056_texteditor_multipage_text_ediots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipage',
            old_name='text_ediots',
            new_name='text_editors',
        ),
    ]
