# Generated by Django 5.1.4 on 2025-09-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_remove_company_facebook_remove_company_linkedin_and_more'),
        ('registration', '0057_rename_text_ediots_multipage_text_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texteditor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_text_editors', to='company.company'),
        ),
        migrations.AlterModelTable(
            name='texteditor',
            table='registration_text_editors',
        ),
    ]
