# Generated by Django 5.1.4 on 2025-09-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_remove_company_facebook_remove_company_linkedin_and_more'),
        ('registration', '0058_alter_texteditor_company_alter_texteditor_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationsubtype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='company.company'),
        ),
    ]
