# Generated by Django 5.1.4 on 2025-09-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0059_alter_registrationsubtype_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipage',
            name='meta_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registrationdetailpage',
            name='meta_title',
            field=models.CharField(max_length=500),
        ),
    ]
