# Generated by Django 5.1.4 on 2025-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0060_alter_multipage_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletpoint',
            name='bullet_point',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='horizontalbullet',
            name='bullet',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='horizontalbullet',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='horizontaltab',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='bullet_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='horizontal_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='registration_region',
            field=models.CharField(default='all', max_length=500),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='table_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='timeline_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='vertical_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipagebulletpoint',
            name='bullet_point',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagebulletpoint',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagefaq',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagefaq',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagefeature',
            name='feature',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagefeature',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagehorizontalbullet',
            name='bullet',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagehorizontalbullet',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipagehorizontalbullet',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagehorizontaltab',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipagehorizontaltab',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagetable',
            name='heading',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagetable',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagetabledata',
            name='data',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagetabledata',
            name='heading',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagetabledata',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagetimeline',
            name='heading',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipagetimeline',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipageverticalbullet',
            name='bullet',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipageverticalbullet',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipageverticalbullet',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipageverticalbullet',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multipageverticaltab',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipageverticaltab',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipageverticaltab',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdetailpage',
            name='bullet_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdetailpage',
            name='horizontal_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdetailpage',
            name='table_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdetailpage',
            name='timeline_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdetailpage',
            name='vertical_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registrationsubtype',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registrationtype',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='table',
            name='heading',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='data',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='heading',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='texteditor',
            name='text_editor_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='texteditor',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='heading',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='verticalbullet',
            name='bullet',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='verticalbullet',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='verticalbullet',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='verticaltab',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='verticaltab',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
