# Generated by Django 5.1.4 on 2025-11-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0062_alter_bulletpoint_bullet_point_alter_enquiry_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsubtype',
            name='ending_slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registrationsubtype',
            name='middle_slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registrationsubtype',
            name='starting_slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
