# Generated by Django 5.1.4 on 2025-11-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0063_registrationsubtype_ending_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationsubtype',
            old_name='middle_slug',
            new_name='location_slug',
        ),
    ]
