# Generated by Django 5.1.4 on 2025-11-06 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_clientslider'),
        ('registration', '0064_rename_middle_slug_registrationsubtype_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipagefaq',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_multipage_faqs', to='company.company'),
        ),
        migrations.CreateModel(
            name='SubTypeFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_type_faqs', to='company.company')),
            ],
            options={
                'db_table': 'sub_type_faqs',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='registrationsubtype',
            name='faqs',
            field=models.ManyToManyField(to='registration.subtypefaq'),
        ),
    ]
