# Generated by Django 5.1.4 on 2025-11-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0065_alter_multipagefaq_company_subtypefaq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsubtype',
            name='hide_faqs',
            field=models.BooleanField(default=False),
        ),
    ]
