# Generated by Django 5.1.4 on 2025-11-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0066_registrationsubtype_hide_faqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtypefaq',
            name='title',
        ),
        migrations.AddField(
            model_name='subtypefaq',
            name='sub_type_slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
