# Generated by Django 5.1.4 on 2025-11-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0067_remove_subtypefaq_title_subtypefaq_sub_type_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsubtype',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
