# Generated by Django 5.1.4 on 2025-11-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0068_registrationsubtype_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationsubtype',
            old_name='ending_slug',
            new_name='ending_title',
        ),
        migrations.RenameField(
            model_name='registrationsubtype',
            old_name='starting_slug',
            new_name='starting_title',
        ),
    ]
