# Generated by Django 5.1.4 on 2025-11-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0069_rename_ending_slug_registrationsubtype_ending_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationsubtype',
            name='ending_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registrationsubtype',
            name='starting_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
