# Generated by Django 5.1.4 on 2025-09-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='meta_title',
            field=models.CharField(max_length=500),
        ),
    ]
