# Generated by Django 5.1.4 on 2025-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homecontent_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='title',
            field=models.CharField(default='BZ India', max_length=500),
        ),
    ]
