# Generated by Django 5.1.4 on 2025-09-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homecontent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='meta_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='title',
            field=models.CharField(default='BZ India', max_length=255),
        ),
    ]
