# Generated by Django 5.1.4 on 2025-10-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='state',
            table='rel_state',
        ),
    ]
