# Generated by Django 5.1.4 on 2025-10-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_state_options_alter_state_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
