# Generated by Django 5.1.4 on 2025-10-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='district',
            name='state_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='district',
            name='state_name',
            field=models.CharField(max_length=150),
        ),
    ]
