# Generated by Django 5.1.4 on 2025-10-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_district_name_alter_district_state_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='state_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
