# Generated by Django 5.1.4 on 2025-10-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_district_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='districts',
            field=models.ManyToManyField(to='home.district'),
        ),
    ]
