# Generated by Django 5.1.4 on 2025-10-09 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_state_districts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='districts',
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='home.state'),
        ),
    ]
