# Generated by Django 5.1.4 on 2025-10-09 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_state_districts_district_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('district_code', models.CharField(max_length=10)),
                ('district_name', models.CharField(blank=True, max_length=150, null=True)),
                ('state_code', models.CharField(max_length=10)),
                ('state_name', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_districts', to='home.district')),
            ],
            options={
                'db_table': 'rel_sub_district',
                'ordering': ['name'],
            },
        ),
    ]
