# Generated by Django 5.1.4 on 2025-10-09 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_subdistrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdistrict',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_districts', to='home.state'),
        ),
    ]
