# Generated by Django 5.1.4 on 2025-10-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(db_index=True, max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='state_code',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
