# Generated by Django 5.1.4 on 2025-10-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_district_code_alter_state_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='district_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='village',
            name='sub_district_code',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
