# Generated by Django 5.1.4 on 2025-10-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_district_code_alter_subdistrict_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=50)),
                ('village_code', models.CharField(max_length=10, unique=True)),
                ('village_name', models.CharField(max_length=150)),
                ('sub_district_code', models.CharField(max_length=10)),
                ('sub_district_name', models.CharField(blank=True, max_length=150, null=True)),
                ('district_code', models.CharField(max_length=10)),
                ('district_name', models.CharField(blank=True, max_length=150, null=True)),
                ('state_code', models.CharField(max_length=10)),
                ('state_name', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'rel_pincode',
                'ordering': ['pincode'],
            },
        ),
    ]
