# Generated by Django 5.1.4 on 2025-10-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_pincode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pincode',
            table='aaa_pincode',
        ),
    ]
