# Generated by Django 5.1.4 on 2025-10-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_village_sub_district_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='sub_district_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
