# Generated by Django 5.1.4 on 2025-10-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_village_sub_district_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='district',
            table='rel_districts',
        ),
        migrations.AlterModelTable(
            name='state',
            table='rel_states',
        ),
        migrations.AlterModelTable(
            name='subdistrict',
            table='rel_sub_districts',
        ),
        migrations.AlterModelTable(
            name='village',
            table='rel_villages',
        ),
    ]
