# Generated by Django 5.1.4 on 2025-10-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_district_table_alter_state_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='pincode',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
