# Generated by Django 5.1.4 on 2025-10-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_pincode_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='pincode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='village_code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
