# Generated by Django 5.1.4 on 2025-10-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_pincode_pincode_alter_pincode_village_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='state_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
