# Generated by Django 5.1.4 on 2025-10-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='longitude',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='json_data',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
