# Generated by Django 5.1.4 on 2025-10-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_coordinates_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
