# Generated by Django 5.1.4 on 2025-10-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_village_latitude_village_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='district_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='village',
            name='sub_district_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['name', 'district_name', 'state_name'], name='rel_village_name_cf3f13_idx'),
        ),
    ]
