# Generated by Django 5.1.4 on 2025-10-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_village_district_name_alter_village_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='is_old_coordinate',
            field=models.BooleanField(default=False),
        ),
    ]
