# Generated by Django 5.1.4 on 2025-10-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_village_is_old_coordinate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='is_old_coordinate',
        ),
    ]
