# Generated by Django 5.1.4 on 2025-09-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_remove_company_facebook_remove_company_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='meta_title',
            field=models.CharField(max_length=500),
        ),
    ]
