# Generated by Django 5.1.4 on 2025-09-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_alter_banner_title_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='url',
            field=models.URLField(blank=True, max_length=220, null=True),
        ),
    ]
