# Generated by Django 5.1.4 on 2025-10-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_alter_client_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_slider_headings', to='company.company')),
            ],
            options={
                'db_table': 'client_sliders',
                'ordering': ['heading'],
            },
        ),
    ]
