# Generated by Django 5.1.4 on 2025-09-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_metatag_meta_description_metatag_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='meta_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
