# Generated by Django 5.1.4 on 2025-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_metatag_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
