# Generated by Django 5.1.4 on 2025-09-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_metatag_name_alter_metatag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
