# Generated by Django 5.1.4 on 2025-09-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0043_indialocationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueplace',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='locations.uniquestate'),
        ),
    ]
