# Generated by Django 5.1.4 on 2025-09-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0044_alter_uniqueplace_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueplace',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='uniqueplace',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
