# Generated by Django 5.1.4 on 2025-10-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0045_alter_uniqueplace_created_alter_uniqueplace_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndianState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'indian_states',
                'ordering': ['name'],
            },
        ),
    ]
