# Generated by Django 5.1.4 on 2025-10-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0047_indiandistrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndianLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('formatted', models.CharField(blank=True, max_length=512, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('country_code', models.CharField(blank=True, max_length=4, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('district', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('town', models.CharField(blank=True, max_length=128, null=True)),
                ('village', models.CharField(blank=True, max_length=128, null=True)),
                ('suburb', models.CharField(blank=True, max_length=128, null=True)),
                ('city_district', models.CharField(blank=True, max_length=128, null=True)),
                ('place', models.CharField(blank=True, max_length=128, null=True)),
                ('place_type', models.CharField(blank=True, help_text='city / town / village / suburb / neighbourhood / etc.', max_length=64, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('iso_codes', models.JSONField(blank=True, null=True)),
                ('json_data', models.JSONField(blank=True, help_text='Raw geocoding API response.', null=True)),
                ('confidence', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='e.g., opencage / geolite2', max_length=64, null=True)),
                ('requested_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('requested_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location Location',
                'verbose_name_plural': 'Location Locations',
                'db_table': 'indian_locations',
                'indexes': [models.Index(fields=['state', 'district'], name='indian_loca_state_50f769_idx'), models.Index(fields=['latitude', 'longitude'], name='indian_loca_latitud_523661_idx'), models.Index(fields=['place'], name='indian_loca_place_93c48c_idx'), models.Index(fields=['postcode'], name='indian_loca_postcod_67a4f3_idx')],
            },
        ),
        migrations.DeleteModel(
            name='IndianDistrict',
        ),
        migrations.DeleteModel(
            name='IndianState',
        ),
    ]
