# Generated by Django 5.1.4 on 2025-10-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0048_indianlocation_delete_indiandistrict_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='indianlocation',
            name='indian_loca_place_93c48c_idx',
        ),
        migrations.RemoveField(
            model_name='indianlocation',
            name='place',
        ),
        migrations.AddField(
            model_name='indianlocation',
            name='county',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
