# Generated by Django 5.1.4 on 2025-10-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0049_remove_indianlocation_indian_loca_place_93c48c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indianlocation',
            name='json_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
