# Generated by Django 5.1.4 on 2025-10-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0050_indianlocation_json_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='indialocationdata',
            name='json_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
