# Generated by Django 5.1.4 on 2025-10-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0051_indialocationdata_json_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indianlocation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='indianlocation',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='indianlocation',
            name='requested_latitude',
        ),
        migrations.RemoveField(
            model_name='indianlocation',
            name='requested_longitude',
        ),
        migrations.AlterField(
            model_name='indianlocation',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indianlocation',
            name='city_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indianlocation',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indianlocation',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='indianlocation',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indianlocation',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indianlocation',
            name='formatted',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='indianlocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indianlocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indianlocation',
            name='place_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indianlocation',
            name='source',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.indialocationdata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indianlocation',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indianlocation',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indianlocation',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indianlocation',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
