# Generated by Django 5.1.4 on 2025-10-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0052_remove_indianlocation_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuburbLocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
                ('address', models.CharField(max_length=500)),
                ('requested_place', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'suburb_location_data',
                'ordering': ['created'],
            },
        ),
        migrations.AlterModelOptions(
            name='indianlocation',
            options={'verbose_name': 'Indian Location', 'verbose_name_plural': 'Indian Locations'},
        ),
    ]
