# Generated by Django 5.1.4 on 2025-10-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0053_suburblocationdata_alter_indianlocation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='suburblocationdata',
            name='json_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
