# Generated by Django 5.1.4 on 2025-10-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0054_suburblocationdata_json_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquedistrict',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='uniquestate',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='uniqueplace',
            index=models.Index(fields=['name', 'district', 'state'], name='unique_plac_name_44a5e9_idx'),
        ),
    ]
