# Generated by Django 5.1.4 on 2025-10-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0056_alter_place_latitude_alter_place_longitude_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='uniqueplace',
            index=models.Index(fields=['slug'], name='unique_plac_slug_7955ae_idx'),
        ),
        migrations.AddIndex(
            model_name='uniqueplace',
            index=models.Index(fields=['district'], name='unique_plac_distric_9bb9ea_idx'),
        ),
    ]
