# Generated by Django 5.1.4 on 2025-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_api', '0003_enquiry_company_sub_type_alter_enquiry_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
