# Generated by Django 5.1.4 on 2025-09-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_api', '0004_alter_enquiry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
