# Generated by Django 5.1.4 on 2025-10-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_api', '0005_alter_enquiry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='item',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
