# Generated by Django 5.1.4 on 2025-10-24 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0047_alter_csccenter_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csccenter',
            options={'ordering': ['name'], 'verbose_name': 'CSC', 'verbose_name_plural': 'CSCs'},
        ),
        migrations.AlterModelTable(
            name='csccenter',
            table='csc_centers',
        ),
    ]
