# Generated by Django 5.1.4 on 2025-10-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0048_alter_csccenter_options_alter_csccenter_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csccenter',
            name='registrations',
        ),
        migrations.AddField(
            model_name='csccenter',
            name='all_registrations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csccenter',
            name='district_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='csccenter',
            name='state_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
