# Generated by Django 5.1.4 on 2025-10-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0049_remove_csccenter_registrations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='csccenter',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csccenter',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csccenter',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
