# Generated by Django 5.1.4 on 2025-10-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0050_alter_csccenter_created_alter_csccenter_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csccenter',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='csccenter',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
