# Generated by Django 5.1.4 on 2025-10-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0051_csccenter_title_alter_csccenter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='csccenter',
            name='place_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
