# Generated by Django 5.1.4 on 2025-10-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0052_csccenter_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='street',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
