# Generated by Django 5.1.4 on 2025-10-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0054_alter_csccenter_latitude_alter_csccenter_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='csccenter',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
