# Generated by Django 5.1.4 on 2025-10-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0055_alter_csccenter_latitude_alter_csccenter_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='csccenter',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
