# Generated by Django 5.1.4 on 2025-10-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0056_alter_csccenter_name_alter_csccenter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='csccenter',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
