# Generated by Django 5.1.4 on 2025-10-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0057_alter_csccenter_name_alter_csccenter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='contact_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='csccenter',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='csccenter',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
