# Generated by Django 5.1.4 on 2025-10-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0058_alter_csccenter_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csccenter',
            name='landmark_or_building_name',
        ),
    ]
