# Generated by Django 5.1.4 on 2025-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0059_remove_csccenter_landmark_or_building_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='csccenter',
            name='decimal_latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='csccenter',
            name='decimal_longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
